### ISSUE TITLE
Does not work with angular 18.0.5

### ISSUE THREAD

**Issue by beig** [ngxpert/avvvatars#4]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Cant install into project

```
npm ERR! Found: @angular/common@18.0.5
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"^18.0.5" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^17.0.0" from @ngxpert/avvvatars@1.0.0
npm ERR! node_modules/@ngxpert/avvvatars
npm ERR!   @ngxpert/avvvatars@"*" from the root project
```

## Expected behavior

Support Angular 18 (and upcoming 18.1)

## What is the motivation / use case for changing the behavior?

I forked the project and tried to update

in projects/ngxpert/avvvatars/package.json
```
    "@angular/common": ">=17.0.0 <=18.0.5",
    "@angular/core": ">=17.0.0 <=18.0.5"
```

and then in package.json angular, eslint, typescript to the latest version but I get

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: @ngxpert/avvvatars@0.0.0-development
npm ERR! Found: @angular-devkit/build-angular@17.0.6
npm ERR! node_modules/@angular-devkit/build-angular
npm ERR!   dev @angular-devkit/build-angular@"^18.0.6" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! dev @angular-devkit/build-angular@"^18.0.6" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: typescript@5.4.5
npm ERR! node_modules/typescript
npm ERR!   peer typescript@">=5.4 <5.5" from @angular-devkit/build-angular@18.0.6
npm ERR!   node_modules/@angular-devkit/build-angular
npm ERR!     dev @angular-devkit/build-angular@"^18.0.6" from the root project

```

## Environment

<pre><code>
Angular version: 18.0.5

For Tooling issues:
- Node version: v22.3.0  
- Platform:  Windows

Others:

</code></pre>

**Comment by beig** [comment]
So I guess this project is dead?

**Comment by shhdharmen** [comment]
I am running a bit busy. PR is welcome for this fix! I think this simply needs an ng update.

**Comment by beig** [comment]
> I am running a bit busy. PR is welcome for this fix! I think this simply needs an ng update.

thanks for your work, as shown, i have tried to update, but i am stuck in a dependency hell after updating

**Comment by shhdharmen** [comment]
@beig I meant this library needs updating to angular 18.
